version: '3.7'
services:
  # my-app:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   networks:
  #   - incrowd
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - incrowd
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - incrowd
volumes:
  mongo-data:
    driver: local
networks:
  incrowd:
    name: incrowd
    driver: bridge